### ISSUE TITLE
The roulette is inaccurate when adding css framework

### ISSUE THREAD

**Issue by RDETB07** [IvanAdmaers/react-casino-roulette#1]
If you have css framework installed like react bootstrap and importing the bootstrap CSS. The roulette becomes inaccurate, so basically when the value is 2 for the roulette it would land to the number beside it. The ball drops diagonally. 

I've tried semantic UI and it's the same result.

tl;dr - Roulette still works properly but visually the ball drops inaccurately.

Installed: 
React
Casino Roulette
React Bootstrap/Semantic UI

**Comment by IvanAdmaers** [comment]
Hi, @RDETB07. Would you mind providing a code example on Sandbox, please?On 8 Sep 2023, at 1:13 a.m., RDETB07 ***@***.***> wrote:﻿
If you have css framework installed like react bootstrap and importing the bootstrap CSS. The roulette becomes inaccurate, so basically when the value is 2 for the roulette it would land to the number beside it. The ball drops diagonally.
I've tried semantic UI and it's the same result.
Installed:
React
Casino Roulette
React Bootstrap/Semantic UI

**Comment by RDETB07** [comment]
https://codesandbox.io/s/react-casino-roulette-example-forked-3zpdrj?file=/src/App.js

![image](https://github.com/IvanAdmaers/react-casino-roulette/assets/44961619/639ab316-0370-4a19-8e5f-7f1cb8ba3c12)
![image](https://github.com/IvanAdmaers/react-casino-roulette/assets/44961619/64b0cc7e-6468-44ce-ad87-e6698a4e376e)

Do a couple of spins and compare w/ and w/o the import of bootstrap.css and you'll see what I mean

**Comment by IvanAdmaers** [comment]
Thank you for this example. I will research this issue over the weekend and come back with an answer

**Comment by IvanAdmaers** [comment]
Hi, @RDETB07. I just added a new prop to the wheel called `addRest`. If you set this to `false` the wheel ball will stop in the center of a winning number. Would you mind setting this to `false` and checking this new behavior in your project?

P.S. Don't forget:

* `npm i react-casino-roulette@1.1.1`
`<RouletteWheel
    ...
   addRest={false} /* This is true by default */
/>`

**Comment by IvanAdmaers** [comment]
Hi again, @RDETB07. I've fixed this issue in version 1.1.2. The issue was related to `line-height`. Bootstrap had set it for the body, and the wheel inherited this, causing the problem. Now I've set its own `line-height` for the wheel, and it works fine, whether Bootstrap is included or not.

Thank you very much for bringing this issue to my attention. If you have any more questions, please feel free to let me know

**Comment by RDETB07** [comment]
Hi @IvanAdmaers, I've tested it and the roulette works now properly with bootstrap. 

Thank you very much for fixing it. Will let you know if I encountered some problems again if ever.
