### ISSUE TITLE
Is it possible to change the color of wheel value field ?

### ISSUE THREAD

**Issue by akshatkumar27** [IvanAdmaers/react-casino-roulette#2]
hello, I am using this library and found out that color on table and wheel for same values are different. Example for 1st the color on table is red but on wheel it's black.

How can I resolve it ?

**Comment by IvanAdmaers** [comment]
Hi, @akshatkumar27. At this moment the color of a field on wheel is getting randomly. Currently you can't change it. I agree that it should be changed and has the same color on table and wheel. I won't be able to change this soon but this issue is my reminder now. So, don't close this, please

**Comment by akshatkumar27** [comment]
Can you assign me this issue I can try to fix it

**Comment by IvanAdmaers** [comment]
Of course. You can always send a pull request if you want to fix it.

**Comment by dozsolti** [comment]
👋 Hi @akshatkumar27 I know I am late to the party but I forked this repo and upgraded it. https://github.com/dozsolti/react-casino-roulette/

One of the upgrades that I did was fixing the colors (also putting the numbers in the right/official order). ✅ 

Another feature that I added is responsiveness, now you can change the height of the table, so the other issue #3 should be also fixed.  ✅

**Comment by IvanAdmaers** [comment]
Hi, guys. Thank you for your contribution to the package.On 7 Dec 2024, at 4:01 p.m., dozsolti ***@***.***> wrote:﻿
👋 Hi @akshatkumar27 I know I am late to the party but I forked this repo and upgraded it. https://github.com/dozsolti/react-casino-roulette/
One of the upgrades that I did was fixing the colors (also putting the numbers in the right/official order). ✅
Another feature that I added is responsiveness, now you can change the height of the table, so the other issue #3 should be also fixed.  ✅

**Comment by IvanAdmaers** [comment]
Thank you for your work, @dozsolti. I've mentioned you in README.

<img width="846" alt="Screenshot 2024-12-09 at 9 57 13 PM" src="https://github.com/user-attachments/assets/26fe7498-8c94-4317-8872-cb54fdf6e0b9">

**Comment by dozsolti** [comment]
> I've mentioned you in README.

I didn't expect this but thank you so much. 😄
