### ISSUE TITLE
Is table column height customizable?

### ISSUE THREAD

**Issue by akshatkumar27** [IvanAdmaers/react-casino-roulette#3]
I want to change the height of last section. All dozens,even,odd,black,red,etc. is it possible?

**Comment by IvanAdmaers** [comment]
Hi. At this moment you can do this only by overriding default css classes.On 22 Nov 2023, at 1:17 p.m., Akshat kumar ***@***.***> wrote:﻿
I want to change the height of last section. All dozens,even,odd,black,red,etc. is it possible?

**Comment by akshatkumar27** [comment]
okay ............Thank you
